-- PostgreSQL production hotfix for CLX-011 screen navigation audit.
-- No business data/model changes. Keeps navigation events immutable and server-only.

CREATE TABLE IF NOT EXISTS public.screen_integration_events(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_ref TEXT UNIQUE NOT NULL,
  ts TEXT NOT NULL,
  actor_role TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  action TEXT NOT NULL,
  screen_id TEXT,
  record_ref TEXT,
  job_ref TEXT,
  detail_json TEXT NOT NULL
);

ALTER TABLE public.screen_integration_events ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.prevent_screen_integration_event_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'IMMUTABLE_SCREEN_EVENT';
END;
$$;

DROP TRIGGER IF EXISTS screen_integration_events_no_update ON public.screen_integration_events;
CREATE TRIGGER screen_integration_events_no_update
BEFORE UPDATE ON public.screen_integration_events
FOR EACH ROW EXECUTE FUNCTION public.prevent_screen_integration_event_mutation();

DROP TRIGGER IF EXISTS screen_integration_events_no_delete ON public.screen_integration_events;
CREATE TRIGGER screen_integration_events_no_delete
BEFORE DELETE ON public.screen_integration_events
FOR EACH ROW EXECUTE FUNCTION public.prevent_screen_integration_event_mutation();

REVOKE ALL ON public.screen_integration_events FROM anon, authenticated;
