-- CLX-075 FINAL BULK ERP COMPLETION + GO-LIVE READINESS
-- Additive only. Existing booking/job/B-L/container/finance/IAM/audit remain authoritative.
-- Production traffic/live providers/real money remain OFF until explicit post-acceptance authorization.

CREATE TABLE IF NOT EXISTS public.equipment_lease_contracts(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contract_ref text NOT NULL UNIQUE,
  provider_type text NOT NULL,
  provider_code text NOT NULL,
  contract_type text NOT NULL DEFAULT 'LEASE',
  currency text NOT NULL DEFAULT 'USD',
  start_date text NOT NULL,
  end_date text,
  minimum_hire_days integer NOT NULL DEFAULT 0,
  free_days integer NOT NULL DEFAULT 0,
  per_diem_rate numeric NOT NULL DEFAULT 0,
  handling_rate numeric NOT NULL DEFAULT 0,
  depot_rate numeric NOT NULL DEFAULT 0,
  lift_on_rate numeric NOT NULL DEFAULT 0,
  lift_off_rate numeric NOT NULL DEFAULT 0,
  drop_off_rate numeric NOT NULL DEFAULT 0,
  pick_up_rate numeric NOT NULL DEFAULT 0,
  damage_responsibility text,
  repair_responsibility text,
  redelivery_terms text,
  offhire_inspection_required boolean NOT NULL DEFAULT true,
  status text NOT NULL DEFAULT 'DRAFT',
  maker_role text NOT NULL,
  checker_role text,
  approved_at text,
  created_at text NOT NULL,
  updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.equipment_lease_allocations(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  allocation_ref text NOT NULL UNIQUE,
  contract_id bigint NOT NULL REFERENCES public.equipment_lease_contracts(id),
  container_id bigint NOT NULL REFERENCES public.containers(id),
  on_hire_date text NOT NULL,
  off_hire_due_date text,
  actual_off_hire_date text,
  extension_until text,
  on_hire_port text,
  off_hire_port text,
  status text NOT NULL DEFAULT 'ON_HIRE',
  accrued_amount numeric NOT NULL DEFAULT 0,
  settled_amount numeric NOT NULL DEFAULT 0,
  settlement_status text NOT NULL DEFAULT 'OPEN',
  created_at text NOT NULL,
  updated_at text NOT NULL,
  UNIQUE(contract_id,container_id,on_hire_date)
);

CREATE TABLE IF NOT EXISTS public.equipment_lease_exceptions(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exception_ref text NOT NULL UNIQUE,
  allocation_id bigint REFERENCES public.equipment_lease_allocations(id),
  container_id bigint REFERENCES public.containers(id),
  exception_type text NOT NULL,
  severity text NOT NULL,
  status text NOT NULL DEFAULT 'OPEN',
  detail text NOT NULL,
  due_date text,
  owner_role text,
  owner_ref text,
  resolution_code text,
  resolution_note text,
  created_at text NOT NULL,
  acknowledged_at text,
  resolved_at text
);
CREATE INDEX IF NOT EXISTS idx_equipment_lease_exception_queue
ON public.equipment_lease_exceptions(status,severity,exception_type,created_at);

CREATE TABLE IF NOT EXISTS public.clx075_readiness_evidence(
  evidence_key text PRIMARY KEY,
  status text NOT NULL,
  category text NOT NULL,
  detail text NOT NULL,
  source_ref text,
  verified_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.clx075_cutover_rehearsals(
  run_ref text PRIMARY KEY,
  started_at text NOT NULL,
  completed_at text,
  status text NOT NULL,
  evidence_json text NOT NULL,
  production_traffic_opened boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.clx075_data_reconciliation(
  run_ref text NOT NULL,
  control_key text NOT NULL,
  source_count numeric NOT NULL DEFAULT 0,
  target_count numeric NOT NULL DEFAULT 0,
  variance numeric NOT NULL DEFAULT 0,
  status text NOT NULL,
  detail text,
  PRIMARY KEY(run_ref,control_key)
);

ALTER TABLE public.equipment_lease_contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment_lease_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment_lease_exceptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clx075_readiness_evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clx075_cutover_rehearsals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clx075_data_reconciliation ENABLE ROW LEVEL SECURITY;
