-- CLX-073 EQUIPMENT COST OPTIMIZATION + REPOSITION EXECUTION INTELLIGENCE
-- Decision/audit layer only. No parallel container inventory, booking model, rate master or execution queue.
-- Existing public.containers, container_events, container_financial_ledger and equipment_work_items remain authoritative.

CREATE TABLE IF NOT EXISTS public.equipment_optimization_runs(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_ref text NOT NULL UNIQUE,
  destination_port text NOT NULL,
  size_type text NOT NULL,
  qty integer NOT NULL CHECK(qty>0),
  required_by text,
  currency text NOT NULL DEFAULT 'USD',
  selected_option_type text,
  selected_source_port text,
  selected_source_depot text,
  selected_source_agent text,
  selected_estimated_cost numeric,
  selected_estimated_lead_days numeric,
  selected_score numeric,
  selected_reason text,
  status text NOT NULL DEFAULT 'DRAFT',
  linked_work_ref text,
  maker_role text NOT NULL,
  checker_role text,
  approved_at text,
  created_at text NOT NULL,
  updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.equipment_optimization_options(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint NOT NULL REFERENCES public.equipment_optimization_runs(id) ON DELETE CASCADE,
  option_ref text NOT NULL UNIQUE,
  option_type text NOT NULL,
  source_port text,
  source_branch text,
  source_agent text,
  source_depot text,
  distance_km numeric NOT NULL DEFAULT 0,
  lead_days numeric NOT NULL DEFAULT 0,
  movement_cost numeric NOT NULL DEFAULT 0,
  handling_cost numeric NOT NULL DEFAULT 0,
  depot_cost numeric NOT NULL DEFAULT 0,
  load_cost numeric NOT NULL DEFAULT 0,
  discharge_cost numeric NOT NULL DEFAULT 0,
  feeder_cost numeric NOT NULL DEFAULT 0,
  truck_cost numeric NOT NULL DEFAULT 0,
  rail_cost numeric NOT NULL DEFAULT 0,
  lease_cost numeric NOT NULL DEFAULT 0,
  detention_idle_impact numeric NOT NULL DEFAULT 0,
  aging_impact numeric NOT NULL DEFAULT 0,
  estimated_total_cost numeric NOT NULL DEFAULT 0,
  expected_turnaround_days numeric NOT NULL DEFAULT 0,
  historical_cost_basis numeric NOT NULL DEFAULT 0,
  source_priority integer NOT NULL DEFAULT 999,
  score numeric NOT NULL DEFAULT 0,
  explanation_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_equipment_optimization_options_run
ON public.equipment_optimization_options(run_id,score,estimated_total_cost);

CREATE TABLE IF NOT EXISTS public.equipment_execution_variance(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_ref text NOT NULL UNIQUE,
  run_ref text,
  option_ref text,
  planned_cost numeric NOT NULL DEFAULT 0,
  actual_cost numeric NOT NULL DEFAULT 0,
  planned_lead_days numeric NOT NULL DEFAULT 0,
  actual_lead_days numeric NOT NULL DEFAULT 0,
  cost_variance numeric NOT NULL DEFAULT 0,
  lead_variance_days numeric NOT NULL DEFAULT 0,
  forecast_qty numeric NOT NULL DEFAULT 0,
  actual_shortage_avoided numeric NOT NULL DEFAULT 0,
  utilization_delta_pct numeric NOT NULL DEFAULT 0,
  reposition_roi numeric NOT NULL DEFAULT 0,
  updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.equipment_optimization_exceptions(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exception_ref text NOT NULL UNIQUE,
  work_ref text,
  run_ref text,
  option_ref text,
  exception_type text NOT NULL,
  severity text NOT NULL,
  status text NOT NULL DEFAULT 'OPEN',
  threshold_value numeric,
  actual_value numeric,
  detail text NOT NULL,
  owner_role text,
  owner_ref text,
  resolution_code text,
  resolution_note text,
  created_at text NOT NULL,
  acknowledged_at text,
  resolved_at text
);
CREATE INDEX IF NOT EXISTS idx_equipment_optimization_exception_queue
ON public.equipment_optimization_exceptions(status,severity,exception_type,created_at);

CREATE TABLE IF NOT EXISTS public.equipment_optimization_policy(
  policy_key text PRIMARY KEY,
  policy_value text NOT NULL,
  description text NOT NULL,
  updated_at text NOT NULL
);
INSERT INTO public.equipment_optimization_policy(policy_key,policy_value,description,updated_at) VALUES
('rate_source','EXISTING_FINANCE_PLUS_SCENARIO_INPUT','Do not create a duplicate rate master; use existing container finance history and governed scenario inputs',now()::text),
('execution_queue','public.equipment_work_items','Approved optimization actions execute only through the existing equipment work-item queue',now()::text),
('actual_cost_source','public.container_financial_ledger','Actual movement cost derives from existing container financial ledger entries',now()::text),
('actual_time_source','public.container_events','Actual reposition lead time derives from existing journey events',now()::text),
('cost_overrun_threshold_pct','15','Generate exception when actual cost exceeds planned cost by threshold percent',now()::text),
('delay_overrun_threshold_days','2','Generate exception when actual lead time exceeds planned lead time by threshold days',now()::text),
('production_traffic','OFF','CLX-073 does not activate production traffic',now()::text)
ON CONFLICT(policy_key) DO UPDATE SET policy_value=EXCLUDED.policy_value,description=EXCLUDED.description,updated_at=EXCLUDED.updated_at;

ALTER TABLE public.equipment_optimization_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment_optimization_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment_execution_variance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment_optimization_exceptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment_optimization_policy ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.equipment_optimization_runs IS 'CLX-073 decision records only; no inventory or rate master.';
COMMENT ON TABLE public.equipment_optimization_options IS 'CLX-073 explainable alternatives; costs reuse existing finance history plus scenario inputs.';
