-- CLX-070 Container Master Global Control + Ownership + Finance
-- Additive only. One M3 ERP, one authoritative Container Master.

ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS owner_type text NOT NULL DEFAULT 'PRINCIPAL';
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS owner_party_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS branch_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS region_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS principal_owner_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS overseas_partner_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS leasing_company_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS investor_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS agent_supplier_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS manufacturer text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS manufacture_date text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS manufacture_year integer;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS csc_validity text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS csc_plate_no text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS classification text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS grade_payload text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS max_gross_weight numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS tare_weight numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS capacity_cbm numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS iso_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS model_no text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS machinery text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS inner_length numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS inner_width numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS inner_height numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS allocate_for_sale boolean NOT NULL DEFAULT false;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS afghan_transit boolean NOT NULL DEFAULT false;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS technical_remarks text;

UPDATE public.containers
SET owner_type = CASE ownership
  WHEN 'OWNED' THEN 'PRINCIPAL'
  WHEN 'LEASED' THEN 'LEASING_COMPANY'
  WHEN 'AGENT' THEN 'AGENT_SUPPLIED'
  WHEN 'SOC' THEN 'SOC'
  ELSE COALESCE(NULLIF(owner_type,''),'PRINCIPAL')
END,
principal_owner_code = CASE WHEN ownership='OWNED' THEN COALESCE(principal_owner_code,principal_code) ELSE principal_owner_code END,
leasing_company_code = CASE WHEN ownership='LEASED' THEN COALESCE(leasing_company_code,supplier_or_lessor) ELSE leasing_company_code END,
agent_supplier_code = CASE WHEN ownership='AGENT' THEN COALESCE(agent_supplier_code,agent_code) ELSE agent_supplier_code END,
owner_party_code = COALESCE(
  owner_party_code,
  CASE ownership
    WHEN 'OWNED' THEN principal_code
    WHEN 'LEASED' THEN supplier_or_lessor
    WHEN 'AGENT' THEN agent_code
    WHEN 'SOC' THEN 'SHIPPER/SOC'
    ELSE principal_code
  END
);

CREATE TABLE IF NOT EXISTS public.container_party_links(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  container_id bigint NOT NULL REFERENCES public.containers(id) ON DELETE CASCADE,
  party_role text NOT NULL,
  party_code text NOT NULL,
  party_name text,
  is_owner boolean NOT NULL DEFAULT false,
  is_custodian boolean NOT NULL DEFAULT false,
  valid_from text,
  valid_to text,
  terms_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL,
  updated_at text NOT NULL,
  UNIQUE(container_id,party_role,party_code)
);
CREATE INDEX IF NOT EXISTS idx_container_party_links_container ON public.container_party_links(container_id,party_role);
CREATE INDEX IF NOT EXISTS idx_container_party_links_party ON public.container_party_links(party_role,party_code);

CREATE TABLE IF NOT EXISTS public.container_financial_entries(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_ref text NOT NULL UNIQUE,
  container_id bigint NOT NULL REFERENCES public.containers(id) ON DELETE RESTRICT,
  job_id bigint REFERENCES public.jobs(id),
  booking_ref text,
  bl_ref text,
  entry_category text NOT NULL,
  charge_code text NOT NULL,
  description text,
  amount numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'USD',
  party_type text,
  party_code text,
  source_type text NOT NULL,
  source_ref text,
  movement_event_ref text,
  status text NOT NULL DEFAULT 'DRAFT',
  maker_role text NOT NULL,
  checker_role text,
  approved_at text,
  posted_at text,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL,
  updated_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_container_financial_container ON public.container_financial_entries(container_id,status,entry_category);
CREATE INDEX IF NOT EXISTS idx_container_financial_job ON public.container_financial_entries(job_id,booking_ref);
CREATE INDEX IF NOT EXISTS idx_container_financial_party ON public.container_financial_entries(party_type,party_code,status);

CREATE TABLE IF NOT EXISTS public.container_share_rules(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_ref text NOT NULL UNIQUE,
  container_id bigint NOT NULL REFERENCES public.containers(id) ON DELETE CASCADE,
  party_type text NOT NULL,
  party_code text NOT NULL,
  basis text NOT NULL DEFAULT 'REVENUE',
  rate_percent numeric NOT NULL DEFAULT 0,
  fixed_amount numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'USD',
  charge_code text,
  valid_from text,
  valid_to text,
  active boolean NOT NULL DEFAULT true,
  maker_role text NOT NULL,
  checker_role text,
  status text NOT NULL DEFAULT 'DRAFT',
  created_at text NOT NULL,
  updated_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_container_share_rules_container ON public.container_share_rules(container_id,active,status);

CREATE TABLE IF NOT EXISTS public.equipment_policy_rules(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_code text NOT NULL UNIQUE,
  action_code text NOT NULL,
  subject_role text NOT NULL,
  scope_type text NOT NULL DEFAULT 'GLOBAL',
  effect text NOT NULL DEFAULT 'ALLOW',
  threshold_amount numeric,
  currency text,
  four_eyes boolean NOT NULL DEFAULT false,
  config_json text NOT NULL DEFAULT '{}',
  active boolean NOT NULL DEFAULT true,
  created_at text NOT NULL,
  updated_at text NOT NULL
);

INSERT INTO public.equipment_policy_rules(rule_code,action_code,subject_role,scope_type,effect,four_eyes,config_json,active,created_at,updated_at)
VALUES
('EQ-VIEW-ADMIN','VIEW','ADMIN','GLOBAL','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-VIEW-SUPER','VIEW','SUPER_ADMIN','GLOBAL','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-VIEW-OPS','VIEW','OPS','GLOBAL','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-VIEW-DOCS','VIEW','DOCS','GLOBAL','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-VIEW-FIN','VIEW','FINANCE','GLOBAL','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-VIEW-AUDIT','VIEW','AUDITOR','GLOBAL','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-VIEW-VIEWER','VIEW','VIEWER','GLOBAL','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-VIEW-AGENT','VIEW','AGENT','AGENT','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-ALLOCATE-OPS','ALLOCATE','OPS','GLOBAL','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-ALLOCATE-ADMIN','ALLOCATE','ADMIN','GLOBAL','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-ALLOCATE-SUPER','ALLOCATE','SUPER_ADMIN','GLOBAL','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-ALLOCATE-AGENT','ALLOCATE','AGENT','AGENT','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-MOVE-OPS','MOVE','OPS','GLOBAL','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-MOVE-AGENT','MOVE','AGENT','AGENT','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-MASTER-ADMIN','MASTER_EDIT','ADMIN','GLOBAL','ALLOW',true,'{}',true,now()::text,now()::text),
('EQ-MASTER-SUPER','MASTER_EDIT','SUPER_ADMIN','GLOBAL','ALLOW',true,'{}',true,now()::text,now()::text),
('EQ-MASTER-OPS','MASTER_EDIT','OPS','GLOBAL','ALLOW',true,'{}',true,now()::text,now()::text),
('EQ-FIN-DRAFT-FIN','FINANCE_CREATE','FINANCE','GLOBAL','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-FIN-DRAFT-OPS','FINANCE_CREATE','OPS','GLOBAL','ALLOW',false,'{}',true,now()::text,now()::text),
('EQ-FIN-DRAFT-AGENT','FINANCE_CREATE','AGENT','AGENT','ALLOW',false,'{"status":"DRAFT_ONLY"}',true,now()::text,now()::text),
('EQ-FIN-APPROVE-FIN','FINANCE_APPROVE','FINANCE','GLOBAL','ALLOW',true,'{}',true,now()::text,now()::text),
('EQ-FIN-APPROVE-ADMIN','FINANCE_APPROVE','ADMIN','GLOBAL','ALLOW',true,'{}',true,now()::text,now()::text),
('EQ-FIN-APPROVE-SUPER','FINANCE_APPROVE','SUPER_ADMIN','GLOBAL','ALLOW',true,'{}',true,now()::text,now()::text)
ON CONFLICT(rule_code) DO NOTHING;

ALTER TABLE public.container_party_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.container_financial_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.container_share_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment_policy_rules ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.container_party_links IS 'All owner/provider/custody parties linked to the one authoritative M3 container record.';
COMMENT ON TABLE public.container_financial_entries IS 'Container-level revenue, cost, commission and sharing ledger linked to Booking/Job/B-L and movement source.';
COMMENT ON TABLE public.container_share_rules IS 'Governed per-container commission/revenue-share terms.';
COMMENT ON TABLE public.equipment_policy_rules IS 'Central M3 Equipment policy matrix; role + scope + action controls.';
