-- CLX-070 FINAL CONTAINER MASTER / GLOBAL EQUIPMENT GOVERNANCE
-- One M3 ERP. One authoritative container record. Additive only.
-- Production traffic/live providers/real money remain OFF.

ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS owner_party_type text NOT NULL DEFAULT 'PRINCIPAL';
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS owner_party_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS branch_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS office_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS custodian_type text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS custodian_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS kind text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS value_amount numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS csc_validity text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS csc_plate_no text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS csc_safety_approval_no text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS manufacturing_no text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS manufacturer text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS manufacture_date text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS manufacture_year integer;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS max_gross_weight numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS tare_weight numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS classification text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS grade_payload text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS capacity numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS stacking_weight numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS iso_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS test_load numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS model_no text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS machinery text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS inner_length numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS inner_width numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS inner_height numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS periodic_inspection_test text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS periodic_inspection_last_date text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS periodic_inspection_due_date text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS tank_kind text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS stacking_capability text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS remarks text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS allocate_for_sale boolean NOT NULL DEFAULT false;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS afghan_transit boolean NOT NULL DEFAULT false;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS verification_status text NOT NULL DEFAULT 'PENDING';
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS purchase_supplier_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS purchase_invoice_no text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS purchase_invoice_date text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS sale_customer_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS sale_invoice_no text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS sale_invoice_date text;

UPDATE public.containers
SET owner_party_type=CASE
  WHEN ownership='LEASED' THEN 'LEASING_COMPANY'
  WHEN ownership='AGENT' THEN 'AGENT_SUPPLIED'
  WHEN ownership='SOC' THEN 'SOC'
  ELSE 'PRINCIPAL'
END
WHERE owner_party_type IS NULL OR owner_party_type='' OR owner_party_type='PRINCIPAL';

UPDATE public.containers
SET owner_party_code=COALESCE(NULLIF(owner_party_code,''),principal_code)
WHERE owner_party_type='PRINCIPAL';

CREATE TABLE IF NOT EXISTS public.container_party_links(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  container_id bigint NOT NULL REFERENCES public.containers(id) ON DELETE CASCADE,
  party_role text NOT NULL,
  party_type text NOT NULL,
  party_code text NOT NULL,
  agreement_ref text,
  valid_from text,
  valid_to text,
  commission_pct numeric NOT NULL DEFAULT 0,
  revenue_share_pct numeric NOT NULL DEFAULT 0,
  cost_share_pct numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'ACTIVE',
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL,
  UNIQUE(container_id,party_role,party_code,valid_from)
);
CREATE INDEX IF NOT EXISTS idx_container_party_links_container ON public.container_party_links(container_id,status);
CREATE INDEX IF NOT EXISTS idx_container_party_links_party ON public.container_party_links(party_type,party_code,status);

CREATE TABLE IF NOT EXISTS public.container_documents(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_ref text NOT NULL UNIQUE,
  container_id bigint NOT NULL REFERENCES public.containers(id) ON DELETE CASCADE,
  document_type text NOT NULL,
  file_name text NOT NULL,
  storage_ref text NOT NULL,
  status text NOT NULL DEFAULT 'ACTIVE',
  uploaded_by text,
  uploaded_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_container_documents_container ON public.container_documents(container_id,status);

CREATE TABLE IF NOT EXISTS public.container_financial_ledger(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_ref text NOT NULL UNIQUE,
  container_id bigint NOT NULL REFERENCES public.containers(id),
  job_id bigint REFERENCES public.jobs(id),
  booking_ref text,
  bl_ref text,
  movement_event_id bigint REFERENCES public.container_events(id),
  entry_type text NOT NULL,
  charge_code text NOT NULL,
  party_type text,
  party_code text,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'USD',
  quantity numeric NOT NULL DEFAULT 1,
  rate numeric NOT NULL DEFAULT 0,
  basis text,
  source_type text NOT NULL,
  source_ref text,
  status text NOT NULL DEFAULT 'ACCRUED',
  created_by text,
  created_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_container_financial_container ON public.container_financial_ledger(container_id,status);
CREATE INDEX IF NOT EXISTS idx_container_financial_job ON public.container_financial_ledger(job_id,booking_ref);
CREATE INDEX IF NOT EXISTS idx_container_financial_party ON public.container_financial_ledger(party_type,party_code,status);

CREATE TABLE IF NOT EXISTS public.container_share_rules(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_ref text NOT NULL UNIQUE,
  container_id bigint REFERENCES public.containers(id),
  owner_party_type text,
  owner_party_code text,
  agent_code text,
  charge_code text,
  share_type text NOT NULL,
  basis text NOT NULL,
  rate_pct numeric NOT NULL DEFAULT 0,
  fixed_amount numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'USD',
  valid_from text,
  valid_to text,
  status text NOT NULL DEFAULT 'ACTIVE',
  maker text,
  checker text,
  created_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_container_share_rules_match ON public.container_share_rules(owner_party_type,owner_party_code,agent_code,status);

CREATE TABLE IF NOT EXISTS public.equipment_system_policies(
  policy_key text PRIMARY KEY,
  policy_value text NOT NULL,
  description text NOT NULL,
  updated_at text NOT NULL
);
INSERT INTO public.equipment_system_policies(policy_key,policy_value,description,updated_at) VALUES
('single_container_master','ENFORCED','One physical container exists once in M3 Container Master',now()::text),
('owner_party_required','ENFORCED','Every container requires explicit economic owner/provider party',now()::text),
('custody_scope','ENFORCED','Branch/Agent/Depot users operate only within assigned custody scope',now()::text),
('global_ho_visibility','ENFORCED','HO/authorized management has global network visibility',now()::text),
('booking_allocation_link','ENFORCED','Container allocation must link to an authoritative Booking/Job',now()::text),
('bl_same_container','ENFORCED','B/L and release flows use the same allocated Container Master records',now()::text),
('maker_checker','ENFORCED','Controlled financial/equipment approvals require four-eyes',now()::text),
('container_financial_ledger','ENFORCED','Revenue, cost, commission, sharing and movement economics are recorded by container',now()::text),
('override_reason_audit','ENFORCED','Any policy override requires authorized role, reason and audit',now()::text)
ON CONFLICT(policy_key) DO UPDATE SET policy_value=EXCLUDED.policy_value,description=EXCLUDED.description,updated_at=EXCLUDED.updated_at;

ALTER TABLE public.container_party_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.container_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.container_financial_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.container_share_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment_system_policies ENABLE ROW LEVEL SECURITY;
