-- CLX-071 FULL CONTAINER JOURNEY + MOVEMENT & EXCEPTION CONTROL
-- Additive extension only: one M3 ERP, one authoritative public.containers record per physical unit.

ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS planned_time text;
ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS actual_time text;
ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS event_phase text NOT NULL DEFAULT 'ACTUAL';
ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS port_code text;
ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS branch_code text;
ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS agent_code text;
ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS depot_code text;
ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS voyage_id bigint;
ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS voyage_ref text;
ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS vessel_name text;
ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS source_work_ref text;
ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS override_used boolean NOT NULL DEFAULT false;
ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS override_reason text;
ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS actor_role text;
ALTER TABLE public.container_events ADD COLUMN IF NOT EXISTS actor_ref text;

UPDATE public.container_events
SET actual_time=COALESCE(actual_time,event_time),event_phase='ACTUAL'
WHERE actual_time IS NULL AND COALESCE(event_phase,'ACTUAL')='ACTUAL';

ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS journey_state text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS last_event_type text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS last_event_time text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS free_days integer NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS free_time_start text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS detention_due_date text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS detention_rate numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS expected_empty_return text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS damage_hold boolean NOT NULL DEFAULT false;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS inspection_hold boolean NOT NULL DEFAULT false;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS journey_updated_at text;

UPDATE public.containers
SET journey_state=COALESCE(NULLIF(journey_state,''),equipment_status),
    last_event_type=COALESCE(last_event_type,equipment_status),
    journey_updated_at=COALESCE(journey_updated_at,updated_at)
WHERE journey_state IS NULL OR journey_state='';

CREATE TABLE IF NOT EXISTS public.container_journey_exceptions(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exception_ref text NOT NULL UNIQUE,
  container_id bigint NOT NULL REFERENCES public.containers(id) ON DELETE CASCADE,
  job_id bigint REFERENCES public.jobs(id),
  exception_type text NOT NULL,
  severity text NOT NULL,
  status text NOT NULL DEFAULT 'OPEN',
  expected_event text,
  actual_state text,
  due_time text,
  detail text NOT NULL,
  owner_role text,
  owner_ref text,
  resolution_code text,
  resolution_note text,
  created_at text NOT NULL,
  acknowledged_at text,
  resolved_at text,
  created_by text
);
CREATE INDEX IF NOT EXISTS idx_container_journey_exc_queue
ON public.container_journey_exceptions(status,severity,exception_type,created_at);
CREATE INDEX IF NOT EXISTS idx_container_journey_exc_container
ON public.container_journey_exceptions(container_id,status);

CREATE TABLE IF NOT EXISTS public.container_journey_policy(
  policy_key text PRIMARY KEY,
  policy_value text NOT NULL,
  description text NOT NULL,
  updated_at text NOT NULL
);
INSERT INTO public.container_journey_policy(policy_key,policy_value,description,updated_at) VALUES
('sequence_validation','ENFORCED','Actual journey events must follow the approved lifecycle unless an authorized override is audited',now()::text),
('custody_transfer','ENFORCED','Branch/agent/depot custody updates use the same Container Master record',now()::text),
('planned_actual','ENFORCED','Planned and actual event timestamps are retained on container events',now()::text),
('movement_cost','ENFORCED','Movement costs accrue to the existing container financial ledger',now()::text),
('detention_clock','ENFORCED','Gate-out-full starts the configured free-day/detention clock',now()::text),
('empty_return_exception','ENFORCED','Overdue empty return generates a governed operations exception',now()::text),
('damage_inspection_hold','ENFORCED','Damage/inspection holds block AVAILABLE status until cleared',now()::text),
('override_audit','ENFORCED','Override requires authorized role, reason and audit event',now()::text)
ON CONFLICT(policy_key) DO UPDATE SET policy_value=EXCLUDED.policy_value,description=EXCLUDED.description,updated_at=EXCLUDED.updated_at;

ALTER TABLE public.container_journey_exceptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.container_journey_policy ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_container_events_journey
ON public.container_events(container_id,event_time,event_type);
CREATE INDEX IF NOT EXISTS idx_container_events_plan
ON public.container_events(container_id,event_phase,planned_time,actual_time);
