-- CLX-072 GLOBAL EQUIPMENT NETWORK + STOCK BALANCING & REPOSITION CONTROL
-- Additive control data only. Physical stock remains authoritative in public.containers.
-- Existing equipment_work_items remains the only governed equipment action queue.
-- Production traffic/live providers/real money remain OFF.

CREATE TABLE IF NOT EXISTS public.equipment_network_targets(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_ref text NOT NULL UNIQUE,
  port_code text NOT NULL,
  branch_code text,
  agent_code text,
  depot_code text,
  size_type text NOT NULL,
  safety_stock integer NOT NULL DEFAULT 0 CHECK(safety_stock>=0),
  target_stock integer NOT NULL DEFAULT 0 CHECK(target_stock>=0),
  reorder_point integer NOT NULL DEFAULT 0 CHECK(reorder_point>=0),
  planning_horizon_days integer NOT NULL DEFAULT 14 CHECK(planning_horizon_days BETWEEN 1 AND 180),
  reposition_lead_days integer NOT NULL DEFAULT 3 CHECK(reposition_lead_days BETWEEN 0 AND 90),
  idle_alert_days integer NOT NULL DEFAULT 14 CHECK(idle_alert_days>=0),
  critical_idle_days integer NOT NULL DEFAULT 30 CHECK(critical_idle_days>=0),
  status text NOT NULL DEFAULT 'ACTIVE',
  maker_role text NOT NULL,
  checker_role text,
  approved_at text,
  created_at text NOT NULL,
  updated_at text NOT NULL,
  UNIQUE(port_code,branch_code,agent_code,depot_code,size_type)
);
CREATE INDEX IF NOT EXISTS idx_equipment_network_targets_lookup
ON public.equipment_network_targets(port_code,size_type,status);

CREATE TABLE IF NOT EXISTS public.equipment_network_policy(
  policy_key text PRIMARY KEY,
  policy_value text NOT NULL,
  description text NOT NULL,
  updated_at text NOT NULL
);
INSERT INTO public.equipment_network_policy(policy_key,policy_value,description,updated_at) VALUES
('authoritative_stock_source','public.containers','All network stock calculations derive from the single authoritative Container Master',now()::text),
('journey_source','public.container_events','Network movement and turnaround use the existing CLX-071 journey events',now()::text),
('action_queue','public.equipment_work_items','Reposition/on-hire/off-hire/shortage execution uses the existing equipment work item queue',now()::text),
('booking_demand','AUTHORITATIVE_BOOKING_JOB_CONTEXT','Demand forecast uses existing Booking/Job requirements and existing equipment actions; no duplicate booking model',now()::text),
('maker_checker','ENFORCED','Network target approval and equipment action approval preserve maker/checker control',now()::text),
('production_traffic','OFF','CLX-072 does not activate production traffic',now()::text)
ON CONFLICT(policy_key) DO UPDATE SET policy_value=EXCLUDED.policy_value,description=EXCLUDED.description,updated_at=EXCLUDED.updated_at;

ALTER TABLE public.equipment_network_targets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment_network_policy ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.equipment_network_targets IS 'CLX-072 planning parameters only; not physical inventory. public.containers remains authoritative.';
COMMENT ON TABLE public.equipment_network_policy IS 'CLX-072 equipment network policy; no duplicate stock or booking data.';
