-- CLX-070 REAL RUNTIME INTEGRATION
-- Additive extension of the existing authoritative public.containers table.
-- Production traffic/live providers/real money remain OFF.

ALTER TABLE public.containers ALTER COLUMN job_id DROP NOT NULL;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS ownership text NOT NULL DEFAULT 'OWNED';
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS principal_code text NOT NULL DEFAULT 'M3 NVOCC';
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS current_port text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS agent_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS depot_code text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS equipment_status text NOT NULL DEFAULT 'AVAILABLE';
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS condition text NOT NULL DEFAULT 'GOOD';
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS available_from text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS booking_ref text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS acquisition_type text NOT NULL DEFAULT 'LEGACY';
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS acquisition_ref text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS lease_contract_ref text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS purchase_order_ref text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS supplier_or_lessor text;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS unit_cost numeric NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'USD';
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS idle_days integer NOT NULL DEFAULT 0;
ALTER TABLE public.containers ADD COLUMN IF NOT EXISTS updated_at text;

UPDATE public.containers c
SET
  current_port = COALESCE(current_port,j.pol),
  agent_code = COALESCE(agent_code,a.code),
  equipment_status = COALESCE(NULLIF(equipment_status,''),'RESERVED'),
  booking_ref = COALESCE(booking_ref,b.booking_ref),
  updated_at = COALESCE(updated_at,now()::text)
FROM public.jobs j
JOIN public.agents a ON a.id=j.agent_id
JOIN public.bookings b ON b.id=j.booking_id
WHERE c.job_id=j.id;

CREATE INDEX IF NOT EXISTS idx_containers_equipment_position
  ON public.containers(current_port,size_type,equipment_status,ownership);
CREATE INDEX IF NOT EXISTS idx_containers_equipment_agent
  ON public.containers(agent_code,depot_code,equipment_status);
CREATE INDEX IF NOT EXISTS idx_containers_booking_ref
  ON public.containers(booking_ref);

CREATE TABLE IF NOT EXISTS public.equipment_work_items(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_ref text NOT NULL UNIQUE,
  work_type text NOT NULL,
  status text NOT NULL,
  booking_ref text,
  job_ref text,
  size_type text NOT NULL,
  qty integer NOT NULL CHECK(qty>0),
  source_port text,
  destination_port text,
  source_agent text,
  destination_agent text,
  source_depot text,
  destination_depot text,
  estimated_cost numeric NOT NULL DEFAULT 0,
  currency text NOT NULL DEFAULT 'USD',
  required_by text,
  payload_json text NOT NULL DEFAULT '{}',
  maker_role text NOT NULL,
  checker_role text,
  decision_note text,
  created_at text NOT NULL,
  updated_at text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_equipment_work_items_queue
  ON public.equipment_work_items(status,work_type,required_by);

ALTER TABLE public.equipment_work_items ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.equipment_work_items IS 'CLX-070 governed workflow records only; physical inventory remains authoritative in public.containers';
