-- CLX-074 DEPOT + INSPECTION + DAMAGE & M&R CONTROL
-- Additive control layer. public.containers, container_documents, container_financial_ledger and equipment_work_items remain authoritative.

CREATE TABLE IF NOT EXISTS public.container_inspections(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 inspection_ref text NOT NULL UNIQUE,
 container_id bigint NOT NULL REFERENCES public.containers(id) ON DELETE CASCADE,
 inspection_type text NOT NULL,
 depot_code text,
 contractor_code text,
 status text NOT NULL DEFAULT 'DRAFT',
 condition_before text,
 condition_after text,
 csc_result text,
 safety_result text,
 cleaning_required boolean NOT NULL DEFAULT false,
 repair_required boolean NOT NULL DEFAULT false,
 reinspect_required boolean NOT NULL DEFAULT false,
 inspected_at text,
 completed_at text,
 maker_role text NOT NULL,
 checker_role text,
 approved_at text,
 created_at text NOT NULL,
 updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.container_damage_items(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 damage_ref text NOT NULL UNIQUE,
 inspection_id bigint NOT NULL REFERENCES public.container_inspections(id) ON DELETE CASCADE,
 component_code text NOT NULL,
 location_code text,
 severity text NOT NULL,
 damage_code text,
 description text,
 photo_document_ref text,
 responsibility_party_type text,
 responsibility_party_code text,
 liability_status text NOT NULL DEFAULT 'UNALLOCATED',
 cleaning_required boolean NOT NULL DEFAULT false,
 repair_required boolean NOT NULL DEFAULT true,
 created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.container_repair_estimates(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 estimate_ref text NOT NULL UNIQUE,
 inspection_id bigint NOT NULL REFERENCES public.container_inspections(id) ON DELETE CASCADE,
 depot_code text,
 contractor_code text,
 currency text NOT NULL DEFAULT 'USD',
 labour_cost numeric NOT NULL DEFAULT 0,
 material_cost numeric NOT NULL DEFAULT 0,
 third_party_cost numeric NOT NULL DEFAULT 0,
 cleaning_cost numeric NOT NULL DEFAULT 0,
 total_estimate numeric NOT NULL DEFAULT 0,
 status text NOT NULL DEFAULT 'DRAFT',
 maker_role text NOT NULL,
 checker_role text,
 decision_note text,
 approved_at text,
 created_at text NOT NULL,
 updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.container_repair_orders(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 work_ref text NOT NULL UNIQUE,
 inspection_id bigint NOT NULL REFERENCES public.container_inspections(id),
 estimate_id bigint REFERENCES public.container_repair_estimates(id),
 container_id bigint NOT NULL REFERENCES public.containers(id),
 status text NOT NULL DEFAULT 'DRAFT',
 planned_start text,
 planned_complete text,
 actual_start text,
 actual_complete text,
 reinspected_at text,
 reinspect_result text,
 actual_labour_cost numeric NOT NULL DEFAULT 0,
 actual_material_cost numeric NOT NULL DEFAULT 0,
 actual_third_party_cost numeric NOT NULL DEFAULT 0,
 actual_cleaning_cost numeric NOT NULL DEFAULT 0,
 actual_total_cost numeric NOT NULL DEFAULT 0,
 equipment_work_ref text,
 created_at text NOT NULL,
 updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.container_mr_exceptions(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 exception_ref text NOT NULL UNIQUE,
 container_id bigint NOT NULL REFERENCES public.containers(id),
 inspection_id bigint REFERENCES public.container_inspections(id),
 repair_work_ref text,
 exception_type text NOT NULL,
 severity text NOT NULL,
 status text NOT NULL DEFAULT 'OPEN',
 threshold_value numeric,
 actual_value numeric,
 detail text NOT NULL,
 owner_role text,
 owner_ref text,
 resolution_code text,
 resolution_note text,
 created_at text NOT NULL,
 acknowledged_at text,
 resolved_at text
);
CREATE INDEX IF NOT EXISTS idx_container_mr_exception_queue ON public.container_mr_exceptions(status,severity,exception_type,created_at);

CREATE TABLE IF NOT EXISTS public.container_mr_policy(
 policy_key text PRIMARY KEY,
 policy_value text NOT NULL,
 description text NOT NULL,
 updated_at text NOT NULL
);
INSERT INTO public.container_mr_policy(policy_key,policy_value,description,updated_at) VALUES
('authoritative_container','public.containers','No parallel container model',now()::text),
('photo_store','public.container_documents','Damage photos reuse existing container document links',now()::text),
('finance_source','public.container_financial_ledger','M&R estimate/actual/liability costs reuse the existing container financial ledger',now()::text),
('execution_queue','public.equipment_work_items','Repair execution links to existing equipment work-item control where required',now()::text),
('estimate_overrun_pct','15','Generate estimate overrun exception above threshold',now()::text),
('repair_overdue_days','2','Generate overdue repair exception above planned completion threshold',now()::text),
('production_traffic','OFF','CLX-074 does not activate production traffic',now()::text)
ON CONFLICT(policy_key) DO UPDATE SET policy_value=EXCLUDED.policy_value,description=EXCLUDED.description,updated_at=EXCLUDED.updated_at;

ALTER TABLE public.container_inspections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.container_damage_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.container_repair_estimates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.container_repair_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.container_mr_exceptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.container_mr_policy ENABLE ROW LEVEL SECURITY;
