-- M3 TEST / DRAFT — HUMAN REVIEW REQUIRED
-- CRT = Change Request Ticket; TRT = Terminal Release Ticket.

CREATE TABLE IF NOT EXISTS public.change_request_tickets(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 ticket_ref text NOT NULL UNIQUE,
 target_module text NOT NULL CHECK(target_module IN ('trt','export-trt','import-trt','transshipment-trt')),
 target_record_id bigint NOT NULL REFERENCES public.transaction_records(id),
 maker_user_id text NOT NULL,
 state text NOT NULL CHECK(state IN ('DRAFT','SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','APPLIED','CLOSED')),
 change_payload_json text NOT NULL,
 reason text NOT NULL,
 financial_posted boolean NOT NULL DEFAULT false,
 closed_period boolean NOT NULL DEFAULT false,
 tax_filed boolean NOT NULL DEFAULT false,
 target_version integer NOT NULL,
 applied_by_user_id text,
 application_mode text,
 reversal_ref text,
 corrected_document_ref text,
 repost_ref text,
 created_at timestamptz NOT NULL,
 updated_at timestamptz NOT NULL,
 version integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.crt_approvals(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 ticket_ref text NOT NULL REFERENCES public.change_request_tickets(ticket_ref),
 approval_role text NOT NULL,
 approver_user_id text,
 approver_type text NOT NULL CHECK(approver_type IN ('HUMAN_USER','EXTERNAL_ADVISOR')),
 external_advisor_ref text,
 decision text NOT NULL CHECK(decision IN ('APPROVED','REJECTED')),
 mfa_verified boolean NOT NULL DEFAULT false,
 comment text,
 evidence_ref text,
 decided_at timestamptz NOT NULL,
 UNIQUE(ticket_ref,approval_role)
);

CREATE TABLE IF NOT EXISTS public.crt_audit(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 event_ref text NOT NULL UNIQUE,
 ticket_ref text NOT NULL REFERENCES public.change_request_tickets(ticket_ref),
 ts timestamptz NOT NULL,
 actor_user_id text NOT NULL,
 action text NOT NULL,
 before_json text,
 after_json text,
 reason text
);

UPDATE public.transaction_records SET module='trt' WHERE module='crt';
UPDATE public.transaction_records SET module='export-trt' WHERE module='export-crt';
UPDATE public.transaction_records SET module='import-trt' WHERE module='import-crt';
UPDATE public.transaction_records SET module='transshipment-trt' WHERE module='transshipment-crt';

ALTER TABLE public.change_request_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crt_approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crt_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.change_request_tickets, public.crt_approvals, public.crt_audit FROM anon, authenticated;
