-- M3 DETENTION REVISION 2 HARDENING
-- Additive only: one child store for immutable detention calculation segments.
-- No new CLX, screen, module, rate engine or invoice engine.

CREATE TABLE IF NOT EXISTS public.detention_segments(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  segment_ref text NOT NULL UNIQUE,
  transaction_id bigint NOT NULL REFERENCES public.transaction_records(id) ON DELETE CASCADE,
  job_id bigint NOT NULL REFERENCES public.jobs(id),
  container_id bigint NOT NULL REFERENCES public.containers(id),
  detention_ref text NOT NULL,
  commercial_direction text NOT NULL CHECK(commercial_direction IN ('AGENT_TO_CUSTOMER','PRINCIPAL_TO_AGENT')),
  stage text NOT NULL CHECK(stage IN ('ADVANCE','ONGOING','ACTUAL')),
  sequence integer NOT NULL CHECK(sequence>=1),
  covered_from text NOT NULL,
  covered_till text NOT NULL,
  segment_days integer NOT NULL CHECK(segment_days>=0),
  cumulative_days integer NOT NULL CHECK(cumulative_days>=0),
  segment_amount numeric NOT NULL CHECK(segment_amount>=0),
  cumulative_amount numeric NOT NULL CHECK(cumulative_amount>=0),
  document_currency text NOT NULL,
  fx_rate numeric NOT NULL CHECK(fx_rate>0),
  base_currency text NOT NULL DEFAULT 'USD',
  base_amount numeric NOT NULL CHECK(base_amount>=0),
  rule_ref text NOT NULL,
  tariff_version integer NOT NULL CHECK(tariff_version>=1),
  tariff_effective_from text,
  tariff_effective_to text,
  tariff_charge_code text NOT NULL,
  rate_group text NOT NULL,
  rate numeric NOT NULL CHECK(rate>=0),
  rate_basis text NOT NULL,
  free_days integer NOT NULL CHECK(free_days>=0),
  calculated_at text NOT NULL,
  calculated_by text NOT NULL,
  calculation_hash text NOT NULL UNIQUE,
  UNIQUE(transaction_id,commercial_direction,sequence),
  UNIQUE(transaction_id,commercial_direction,stage,covered_from,covered_till,rule_ref,tariff_version)
);

CREATE INDEX IF NOT EXISTS idx_detention_segments_tx_direction
ON public.detention_segments(transaction_id,commercial_direction,sequence);

CREATE INDEX IF NOT EXISTS idx_detention_segments_container
ON public.detention_segments(container_id,commercial_direction,covered_till);

ALTER TABLE public.detention_segments ENABLE ROW LEVEL SECURITY;

INSERT INTO public.md_config(id,config_key,config_value,value_type,scope,status,version)
SELECT COALESCE(MAX(id),0)+1,'DETENTION_CALCULATION_ENABLED','true','BOOLEAN','GLOBAL','ACTIVE',1
FROM public.md_config
WHERE NOT EXISTS (
  SELECT 1 FROM public.md_config WHERE config_key='DETENTION_CALCULATION_ENABLED' AND scope='GLOBAL'
);
