-- M3 TEST / DRAFT — HUMAN REVIEW REQUIRED
-- Item 1: permanent Job-creation idempotency only.
-- No production execution is performed by AI.

CREATE TABLE IF NOT EXISTS public.job_creation_idempotency (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_key text NOT NULL UNIQUE,
  booking_ref text NOT NULL,
  purpose text NOT NULL,
  split_sequence integer NOT NULL CHECK (split_sequence >= 1),
  consolidation_ref text NOT NULL DEFAULT '',
  request_hash text NOT NULL,
  status text NOT NULL CHECK (status IN ('IN_PROGRESS','CREATED','FAILED')),
  job_id bigint REFERENCES public.jobs(id),
  job_ref text,
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  last_error text,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  created_by text NOT NULL,
  UNIQUE (booking_ref, purpose, split_sequence, consolidation_ref)
);

CREATE INDEX IF NOT EXISTS idx_job_creation_idempotency_job
  ON public.job_creation_idempotency(job_id);

ALTER TABLE public.job_creation_idempotency ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.job_creation_idempotency FROM anon, authenticated;
