-- M3 TEST / DRAFT — HUMAN REVIEW REQUIRED
-- Item 5: HBL + container-level release governance beneath existing nvocc_release_controls.

CREATE TABLE IF NOT EXISTS public.nvocc_release_container_control(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_ref text NOT NULL REFERENCES public.nvocc_release_controls(release_ref),
  container_no text NOT NULL,
  status text NOT NULL CHECK(status IN (
    'BLOCKED','PENDING','CONDITIONAL','PARTIALLY_RELEASED','RELEASED',
    'RELEASED_WITH_POST_DELIVERY_HOLD','REVOKED','EXPIRED'
  )),
  condition_type text CHECK(condition_type IS NULL OR condition_type IN (
    'BG','LOI','CREDIT_OVERRIDE','ORIGINAL_WAIVER','MANAGEMENT_APPROVAL','CUSTOMS_CONDITIONAL'
  )),
  condition_reason text,
  condition_valid_until timestamptz,
  condition_approver_user_id text,
  blocking_reasons_json text NOT NULL DEFAULT '[]',
  delivered_at_action boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  version integer NOT NULL DEFAULT 1,
  UNIQUE(release_ref,container_no)
);

CREATE TABLE IF NOT EXISTS public.nvocc_release_events(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_ref text NOT NULL UNIQUE,
  release_ref text NOT NULL REFERENCES public.nvocc_release_controls(release_ref),
  container_no text NOT NULL,
  from_state text NOT NULL,
  to_state text NOT NULL,
  action text NOT NULL,
  actor_user_id text NOT NULL,
  reason text,
  detail_json text NOT NULL,
  created_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_release_container_status
  ON public.nvocc_release_container_control(release_ref,status,container_no);
CREATE INDEX IF NOT EXISTS idx_release_events_ref
  ON public.nvocc_release_events(release_ref,created_at);

ALTER TABLE public.nvocc_release_container_control ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nvocc_release_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.nvocc_release_container_control,public.nvocc_release_events FROM anon,authenticated;

CREATE OR REPLACE FUNCTION public.m3_release_event_immutable()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'RELEASE_EVENT_IMMUTABLE';
END;
$$;

DROP TRIGGER IF EXISTS trg_release_event_immutable_update ON public.nvocc_release_events;
CREATE TRIGGER trg_release_event_immutable_update
BEFORE UPDATE ON public.nvocc_release_events
FOR EACH ROW EXECUTE FUNCTION public.m3_release_event_immutable();

DROP TRIGGER IF EXISTS trg_release_event_immutable_delete ON public.nvocc_release_events;
CREATE TRIGGER trg_release_event_immutable_delete
BEFORE DELETE ON public.nvocc_release_events
FOR EACH ROW EXECUTE FUNCTION public.m3_release_event_immutable();
