-- M3 TEST / DRAFT — HUMAN REVIEW REQUIRED
-- Item 3: cardinality + operational grouping relationship layer only.

CREATE TABLE IF NOT EXISTS public.operational_groups(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_ref text NOT NULL UNIQUE,
  group_type text NOT NULL CHECK(group_type IN ('CONSOLIDATION','TS','VESSEL','TERMINAL','CRO_TRT')),
  authority_scope text NOT NULL CHECK(authority_scope='OPERATIONAL_COORDINATION_ONLY'),
  created_by text NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.operational_group_jobs(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.operational_groups(id) ON DELETE CASCADE,
  job_id bigint NOT NULL REFERENCES public.jobs(id),
  relationship_status text NOT NULL CHECK(relationship_status IN ('ACTIVE','REMOVED')),
  created_at timestamptz NOT NULL,
  UNIQUE(group_id,job_id)
);

CREATE TABLE IF NOT EXISTS public.mbl_hbl_links(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mbl_bill_id bigint NOT NULL REFERENCES public.bills(id),
  hbl_bill_id bigint NOT NULL REFERENCES public.bills(id),
  job_id bigint NOT NULL REFERENCES public.jobs(id),
  link_status text NOT NULL CHECK(link_status IN ('ACTIVE','REMOVED')),
  created_by text NOT NULL,
  created_at timestamptz NOT NULL,
  UNIQUE(mbl_bill_id,hbl_bill_id),
  CHECK(mbl_bill_id<>hbl_bill_id)
);

CREATE TABLE IF NOT EXISTS public.cro_container_links(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cro_transaction_id bigint NOT NULL REFERENCES public.transaction_records(id),
  container_id bigint NOT NULL REFERENCES public.containers(id),
  relationship_status text NOT NULL CHECK(relationship_status IN ('ACTIVE','REMOVED')),
  created_by text NOT NULL,
  created_at timestamptz NOT NULL,
  UNIQUE(cro_transaction_id,container_id)
);

CREATE TABLE IF NOT EXISTS public.cro_trt_links(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cro_transaction_id bigint NOT NULL REFERENCES public.transaction_records(id),
  trt_transaction_id bigint NOT NULL REFERENCES public.transaction_records(id),
  relationship_status text NOT NULL CHECK(relationship_status IN ('ACTIVE','REMOVED')),
  created_by text NOT NULL,
  created_at timestamptz NOT NULL,
  UNIQUE(cro_transaction_id,trt_transaction_id)
);

CREATE TABLE IF NOT EXISTS public.trt_container_links(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trt_transaction_id bigint NOT NULL REFERENCES public.transaction_records(id),
  container_id bigint NOT NULL REFERENCES public.containers(id),
  relationship_status text NOT NULL CHECK(relationship_status IN ('ACTIVE','REMOVED')),
  created_by text NOT NULL,
  created_at timestamptz NOT NULL,
  UNIQUE(trt_transaction_id,container_id)
);

CREATE INDEX IF NOT EXISTS idx_operational_group_jobs_job ON public.operational_group_jobs(job_id);
CREATE INDEX IF NOT EXISTS idx_mbl_hbl_job ON public.mbl_hbl_links(job_id);
CREATE INDEX IF NOT EXISTS idx_cro_container_container ON public.cro_container_links(container_id);
CREATE INDEX IF NOT EXISTS idx_trt_container_container ON public.trt_container_links(container_id);

ALTER TABLE public.operational_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operational_group_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mbl_hbl_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cro_container_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cro_trt_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trt_container_links ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE
  public.operational_groups,
  public.operational_group_jobs,
  public.mbl_hbl_links,
  public.cro_container_links,
  public.cro_trt_links,
  public.trt_container_links
FROM anon, authenticated;
