-- M3 TEST / DRAFT — HUMAN REVIEW REQUIRED
-- Item 2: Standard / Split / Consolidation Job relationships.
-- No production execution by AI.

-- Permit one Booking to participate in multiple Jobs.
DO $$
DECLARE c record;
BEGIN
  FOR c IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid='public.jobs'::regclass
      AND contype='u'
      AND conkey = ARRAY[
        (SELECT attnum FROM pg_attribute
         WHERE attrelid='public.jobs'::regclass AND attname='booking_id')
      ]
  LOOP
    EXECUTE format('ALTER TABLE public.jobs DROP CONSTRAINT %I', c.conname);
  END LOOP;
END $$;

CREATE TABLE IF NOT EXISTS public.job_mode_profiles (
  job_id bigint PRIMARY KEY REFERENCES public.jobs(id),
  job_type text NOT NULL CHECK(job_type IN ('STANDARD','CONSOLIDATION')),
  consolidation_ref text NOT NULL DEFAULT '',
  split_sequence integer NOT NULL DEFAULT 1 CHECK(split_sequence>=1),
  commercial_authority text NOT NULL DEFAULT 'JOB_BOOKING_LINKS',
  booking_set_hash text,
  version integer NOT NULL DEFAULT 1
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_job_mode_consolidation_ref
  ON public.job_mode_profiles(consolidation_ref)
  WHERE job_type='CONSOLIDATION' AND consolidation_ref<>'';

CREATE TABLE IF NOT EXISTS public.job_booking_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id bigint NOT NULL REFERENCES public.jobs(id),
  booking_id bigint NOT NULL REFERENCES public.bookings(id),
  source_sequence integer NOT NULL CHECK(source_sequence>=1),
  relationship_status text NOT NULL CHECK(relationship_status IN ('ACTIVE','REMOVED')),
  UNIQUE(job_id,booking_id),
  UNIQUE(job_id,source_sequence)
);

CREATE INDEX IF NOT EXISTS idx_job_booking_links_booking
  ON public.job_booking_links(booking_id);

ALTER TABLE public.job_mode_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_booking_links ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.job_mode_profiles FROM anon, authenticated;
REVOKE ALL ON TABLE public.job_booking_links FROM anon, authenticated;
