-- M3 TEST / DRAFT — HUMAN REVIEW REQUIRED
-- Item 4: state transition governance.

CREATE TABLE IF NOT EXISTS public.state_transition_events(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_ref text NOT NULL UNIQUE,
  subject_type text NOT NULL,
  subject_ref text NOT NULL,
  from_state text NOT NULL,
  to_state text NOT NULL,
  mode text NOT NULL CHECK(mode IN ('STANDARD','CORRECTION','OVERRIDE','EXCEPTION_RESOLUTION')),
  actor_user_id text NOT NULL,
  actor_role text NOT NULL,
  reason text,
  evidence_json text NOT NULL DEFAULT '[]',
  approver_user_ids_json text NOT NULL DEFAULT '[]',
  source_event_ref text,
  financial_posted boolean NOT NULL DEFAULT false,
  outcome text NOT NULL CHECK(outcome IN ('ALLOWED','BLOCKED')),
  created_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_state_transition_subject
  ON public.state_transition_events(subject_type,subject_ref,created_at);

ALTER TABLE public.state_transition_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.state_transition_events FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.m3_state_transition_immutable()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'STATE_TRANSITION_HISTORY_IMMUTABLE';
END;
$$;

DROP TRIGGER IF EXISTS trg_state_transition_immutable_update ON public.state_transition_events;
CREATE TRIGGER trg_state_transition_immutable_update
BEFORE UPDATE ON public.state_transition_events
FOR EACH ROW EXECUTE FUNCTION public.m3_state_transition_immutable();

DROP TRIGGER IF EXISTS trg_state_transition_immutable_delete ON public.state_transition_events;
CREATE TRIGGER trg_state_transition_immutable_delete
BEFORE DELETE ON public.state_transition_events
FOR EACH ROW EXECUTE FUNCTION public.m3_state_transition_immutable();
